=== ChiriacAlina/Selenium/regression.dtd
<!ELEMENT suite (test)>
<!ATTLIST suite name CDATA #REQUIRED>
<!ELEMENT test (groups,classes)>
<!ATTLIST test name NMTOKEN #REQUIRED>
<!ELEMENT groups (define+,run)>
<!ELEMENT define (include+)>
<!ATTLIST define name NMTOKEN #REQUIRED>
<!ELEMENT include EMPTY>
<!ATTLIST include name NMTOKEN #REQUIRED>
<!ELEMENT run (include)>
<!ELEMENT classes (class)>
<!ELEMENT class EMPTY>
<!ATTLIST class name NMTOKEN #REQUIRED>

=== ChiriacAlina/Selenium/regression.xml
<!DOCTYPE suite SYSTEM "regression.dtd">
<suite name="Regression TestSuite">
	<test name="GroupsDemo">
	<groups>
		<define name="all">
			<include name="bikes"></include>
			<include name="suv"></include>
			<include name="sedan"></include>
		</define>
		<define name="nobikes">
			<include name="suv"></include>
			<include name="sedan"></include>
		</define>
			<run>
				<include name="all"></include>
			</run>
	</groups>
		<classes>
			<class name="com.expedia.flightbooking.TestNG_Grouping"></class>
		</classes>
	</test>
</suite>
